### ISSUE TITLE
Doesn't autocomplete `docker image prune`

### ISSUE THREAD

**Issue by arthurkarganyan** [ankitsumitg/docker-fish-completions#2]
When doing `docker image pr<Tab>`, no prune is there

**Comment by ankitsumitg** [comment]
Yes, it can be that case.
 
I'm following the official docker repo fish completions. 

You can raise the issue there, they would be able to help and fix the issue.

This repo should auto update in next CD run if official repo gets updated and you can just update the plugin via fisher.

**Comment by arthurkarganyan** [comment]
@ankitsumitg Thanks for your reply. I've looked into the repo and saw `workflow.yml` and now I understand how it works. So, It would be the same as if I  just did `curl https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish > ~/.config/fish/completions/docker.fish` locally, without any plugins.

**Comment by ankitsumitg** [comment]
Yes, absolutely right @arthurkarganyan ... 
I just automated the task to fetch latest docker fish completions and installation via fisher.
